-- QA Script: End-to-End Checkout Validation

-- 1. Verify the most recent invoices and the customer who placed them
SELECT 
    i.invoice_number, 
    i.total, 
    i.status,
    u.first_name, 
    u.last_name, 
    u.email
FROM invoices i
JOIN users u ON i.user_id = u.id
ORDER BY i.created_at DESC
LIMIT 5;

-- 2. Aggregation: Find the total revenue generated by testing today
SELECT SUM(total) AS total_revenue, COUNT(id) AS total_orders
FROM invoices
WHERE DATE(created_at) = CURDATE();